import Head from "next/head";
// import Example from "../components/Example";
import Footer from "../components/Footer";
import Main from "../components/Main";
import Navbar from "../components/Navbar";
import Pricing from "../components/Pricing";
import Step from "../components/Step";
import Teams from "../components/Teams";
import Why from "../components/Why";
import Intro from "./../components/Intro";
import { auth } from "../src/firebase";
import { useAuthState } from "react-firebase-hooks/auth";
import Homes from "./Homes";
import App from "./App";

export default function Home() {
  const [user] = useAuthState(auth);
  console.log(user);

  return (
    <div>
      <Head>
        <title>Kelas Online Front end web developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        {user ?  <Homes/> : <App />}
        {/* <Navbar />
        <Intro />
        <Why />
        <Main />
        <Step />
        <Teams />
        <Pricing />
        <Footer /> */}
        {/* {user ? (
          <>
          </>
        ) : (
          <Homes />
        )} */}
      </>
    </div>
  );
}
