import Head from "next/head";
// import Example from "../components/Example";
import Footer from "../components/Footer";
import Main from "../components/Main";
import Navbar from "../components/Navbar";
import Pricing from "../components/Pricing";
import Step from "../components/Step";
import Teams from "../components/Teams";
import Why from "../components/Why";
import Intro from "./../components/Intro";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kelas Online Front end web developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Navbar />
        <Intro />
        <Why />
        <Main />
        <Step />
        {/* <Example /> */}
        <Teams />
        <Pricing />
        <Footer />
      </>
    </div>
  );
}
